from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.forecast import Forecast
from app.schemas.forecast import ForecastResponse, ForecastCreate

router = APIRouter(prefix="/forecast", tags=["forecast"])

@router.get("/", response_model=list[ForecastResponse])
def get_forecast(db: Session = Depends(get_db)):
    forecasts = db.query(Forecast).all()
    if not forecasts:
        raise HTTPException(status_code=404, detail="No forecast data found")
    return forecasts

#just for testing, in production this would be generated by the ML model and not created via API
# it should be changed to ForecastCreate and not return the model_version, as that is only for internal use to explain the recommendation to the user and should not be stored in the database
@router.post("/", response_model=ForecastResponse)
def create_forecast(forecast: ForecastCreate, db: Session = Depends(get_db)):
    db_forecast = Forecast(
        product_id=forecast.product_id,
        forecast_date=forecast.forecast_date,
        predicted_demand=forecast.predicted_demand,
        model_version=forecast.model_version
    )
    db.add(db_forecast)
    db.commit()
    db.refresh(db_forecast)
    return db_forecast