from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy.orm import Session

from app.database import get_db
from app.models.forecast import Forecast
from app.schemas.forecast import ForecastResponse, ForecastCreate
from app.services.forecast_service import generate_baseline_forecasts


router = APIRouter(prefix="/forecast", tags=["forecast"])
BASELINE_MODEL_VERSION = "baseline-v1"


@router.get("/", response_model=list[ForecastResponse])
def get_forecast(db: Session = Depends(get_db)):
    forecasts = db.query(Forecast).all()

    if not forecasts:
        raise HTTPException(status_code=404, detail="No forecast data found")

    return forecasts


@router.get("/latest", response_model=list[ForecastResponse])
def get_latest_forecasts(db: Session = Depends(get_db)):
    forecasts = db.query(Forecast).all()

    if not forecasts:
        raise HTTPException(status_code=404, detail="No forecast data found")

    latest_by_product_id = {}

    for forecast in forecasts:
        existing_forecast = latest_by_product_id.get(forecast.product_id)

        if not existing_forecast:
            latest_by_product_id[forecast.product_id] = forecast
            continue

        forecast_is_baseline = forecast.model_version == BASELINE_MODEL_VERSION
        existing_is_baseline = (
            existing_forecast.model_version == BASELINE_MODEL_VERSION
        )

        if forecast_is_baseline and not existing_is_baseline:
            latest_by_product_id[forecast.product_id] = forecast
            continue

        if forecast_is_baseline == existing_is_baseline:
            if (
                forecast.forecast_date > existing_forecast.forecast_date
                or (
                    forecast.forecast_date == existing_forecast.forecast_date
                    and forecast.id > existing_forecast.id
                )
            ):
                latest_by_product_id[forecast.product_id] = forecast

    return list(latest_by_product_id.values())

@router.post("/generate")
def generate_forecasts(db: Session = Depends(get_db)):
    return generate_baseline_forecasts(db)

# Just for testing. In production, forecasts should be generated by the ML pipeline.
@router.post("/", response_model=ForecastResponse)
def create_forecast(forecast: ForecastCreate, db: Session = Depends(get_db)):
    db_forecast = Forecast(
        product_id=forecast.product_id,
        forecast_date=forecast.forecast_date,
        predicted_demand=forecast.predicted_demand,
        model_version=forecast.model_version,
    )

    db.add(db_forecast)
    db.commit()
    db.refresh(db_forecast)

    return db_forecast