from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.recommendation import Recommendation
from app.schemas.recommendation import RecommendationResponse   

router = APIRouter(prefix="/recommendations", tags=["recommendations"])

@router.get("/", response_model=list[RecommendationResponse])
def get_recommendations(db: Session = Depends(get_db)):
    recommendations = db.query(Recommendation).all()
    if not recommendations:
        raise HTTPException(status_code=404, detail="No recommendations found")
    return recommendations

#just for testing, in production this would be generated by the ML model and not created via API
# it should be chaneg to RecommendationCreate and not return the reason, as that is only for internal use to explain the recommendation to the user and should not be stored in the database
@router.post("/", response_model=RecommendationResponse)
def create_recommendation(recommendation: RecommendationResponse, db: Session = Depends(get_db)):
    db_recommendation = Recommendation(
        product_id=recommendation.product_id,
        recommended_quantity=recommendation.recommended_quantity,
        reason=recommendation.reason,
    )
    db.add(db_recommendation)
    db.commit()
    db.refresh(db_recommendation)
    return db_recommendation