from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.auth.security import get_current_user
from app.database import get_db
from app.models.forecast import Forecast
from app.models.inventories import Inventory
from app.models.product import Product
from app.models.recommendation import Recommendation
from app.models.user import User
from app.schemas.recommendation import RecommendationCreate, RecommendationResponse

router = APIRouter(prefix="/recommendations", tags=["recommendations"])


@router.get("/", response_model=list[RecommendationResponse])
def get_recommendations(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    recommendations = (
        db.query(Recommendation)
        .filter(Recommendation.user_id == current_user.id)
        .all()
    )

    return recommendations

# Just for testing. In production, recommendations should be generated by the recommendation engine.
@router.post("/", response_model=RecommendationResponse)
def create_recommendation(
    recommendation: RecommendationCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    product = (
        db.query(Product)
        .filter(
            Product.id == recommendation.product_id,
            Product.user_id == current_user.id,
        )
        .first()
    )

    if not product:
        raise HTTPException(status_code=404, detail="Product not found")

    db_recommendation = Recommendation(
        user_id=current_user.id,
        product_id=recommendation.product_id,
        recommended_quantity=recommendation.recommended_quantity,
        reason=recommendation.reason,
    )
    db.add(db_recommendation)
    db.commit()
    db.refresh(db_recommendation)

    return db_recommendation


@router.post("/generate/{product_id}", response_model=RecommendationResponse)
def generate_recommendation(
    product_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    product = (
        db.query(Product)
        .filter(
            Product.id == product_id,
            Product.user_id == current_user.id,
        )
        .first()
    )

    if not product:
        raise HTTPException(status_code=404, detail="Product not found")

    forecast = (
        db.query(Forecast)
        .filter(
            Forecast.user_id == current_user.id,
            Forecast.product_id == product_id,
            Forecast.model_version == "baseline-v1",
        )
        .order_by(Forecast.forecast_date.desc(), Forecast.id.desc())
        .first()
    )

    inventory = (
        db.query(Inventory)
        .filter(Inventory.product_id == product_id)
        .first()
    )

    if not forecast or not inventory:
        raise HTTPException(
            status_code=404,
            detail="Forecast or Inventory data not found for the product",
        )

    if inventory.current_stock <= product.reorder_threshold:
        recommended_quantity = max(
            int(forecast.predicted_demand - inventory.current_stock),
            0,
        )
    else:
        recommended_quantity = 0

    reason = (
        f"Current inventory is {inventory.current_stock}, "
        f"forecasted demand is {forecast.predicted_demand}. "
        f"Recommended quantity is {recommended_quantity}."
    )

    existing_recommendation = (
        db.query(Recommendation)
        .filter(
            Recommendation.user_id == current_user.id,
            Recommendation.product_id == product_id,
        )
        .first()
    )

    if existing_recommendation:
        existing_recommendation.recommended_quantity = recommended_quantity
        existing_recommendation.reason = reason
        db.commit()
        db.refresh(existing_recommendation)

        return existing_recommendation

    db_recommendation = Recommendation(
        user_id=current_user.id,
        product_id=product_id,
        recommended_quantity=recommended_quantity,
        reason=reason,
    )

    db.add(db_recommendation)
    db.commit()
    db.refresh(db_recommendation)

    return db_recommendation


@router.post("/generate_all", response_model=list[RecommendationResponse])
def generate_recommendations_for_all_products(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    products = (
        db.query(Product)
        .filter(Product.user_id == current_user.id)
        .all()
    )

    recommendations = []

    for product in products:
        forecast = (
            db.query(Forecast)
            .filter(
                Forecast.user_id == current_user.id,
                Forecast.product_id == product.id,
                Forecast.model_version == "baseline-v1",
            )
            .order_by(Forecast.forecast_date.desc(), Forecast.id.desc())
            .first()
        )

        inventory = (
            db.query(Inventory)
            .filter(Inventory.product_id == product.id)
            .first()
        )

        if not forecast or not inventory:
            continue

        if inventory.current_stock <= product.reorder_threshold:
            recommended_quantity = max(
                int(forecast.predicted_demand) - inventory.current_stock,
                0,
            )
        else:
            recommended_quantity = 0

        reason = (
            f"Current inventory is {inventory.current_stock}, "
            f"forecasted demand is {forecast.predicted_demand}. "
            f"Recommended quantity is {recommended_quantity}."
        )

        existing_recommendation = (
            db.query(Recommendation)
            .filter(
                Recommendation.user_id == current_user.id,
                Recommendation.product_id == product.id,
            )
            .first()
        )

        if existing_recommendation:
            existing_recommendation.recommended_quantity = recommended_quantity
            existing_recommendation.reason = reason
            recommendations.append(existing_recommendation)
        else:
            db_recommendation = Recommendation(
                user_id=current_user.id,
                product_id=product.id,
                recommended_quantity=recommended_quantity,
                reason=reason,
            )
            db.add(db_recommendation)
            recommendations.append(db_recommendation)

    db.commit()

    for recommendation in recommendations:
        db.refresh(recommendation)

    return recommendations