from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.auth.security import get_current_user
from app.database import get_db
from app.models.forecast import Forecast
from app.models.inventories import Inventory
from app.models.product import Product
from app.models.recommendation import Recommendation
from app.models.user import User
from app.schemas.recommendation import RecommendationCreate, RecommendationResponse
from app.services.forecast_service import MODEL_VERSION
from app.services.risk_service import calculate_demand_risk_score, get_risk_level

router = APIRouter(prefix="/recommendations", tags=["recommendations"])


def build_recommendation_response(
    recommendation: Recommendation,
    product_name: str,
    risk_level: str | None = None,
    risk_score: int | None = None,
) -> dict:
    return {
        "id": recommendation.id,
        "user_id": recommendation.user_id,
        "product_id": recommendation.product_id,
        "product_name": product_name,
        "recommended_quantity": recommendation.recommended_quantity,
        "reason": recommendation.reason,
        "created_at": recommendation.created_at,
        "risk_level": risk_level,
        "risk_score": risk_score,
    }


def calculate_recommendation_risk(
    inventory: Inventory,
    product: Product,
    forecast: Forecast,
    recommended_quantity,
) -> tuple[str, int]:
    risk_score = calculate_demand_risk_score(
        current_stock=inventory.current_stock,
        reorder_threshold=product.reorder_threshold,
        predicted_demand=forecast.predicted_demand,
        recommended_quantity=recommended_quantity,
    )

    return get_risk_level(risk_score), risk_score


@router.get("/", response_model=list[RecommendationResponse])
def get_recommendations(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    recommendation_rows = (
        db.query(Recommendation, Product.name)
        .join(Product, Product.id == Recommendation.product_id)
        .filter(
            Recommendation.user_id == current_user.id,
            Product.user_id == current_user.id,
        )
        .order_by(
            Recommendation.recommended_quantity.desc(),
            Product.name.asc(),
            Recommendation.id.desc(),
        )
        .all()
    )

    return [
        build_recommendation_response(recommendation, product_name)
        for recommendation, product_name in recommendation_rows
    ]


# Just for testing. In production, recommendations should be generated by the recommendation engine.
@router.post("/", response_model=RecommendationResponse)
def create_recommendation(
    recommendation: RecommendationCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    product = (
        db.query(Product)
        .filter(
            Product.id == recommendation.product_id,
            Product.user_id == current_user.id,
        )
        .first()
    )

    if not product:
        raise HTTPException(status_code=404, detail="Product not found")

    db_recommendation = Recommendation(
        user_id=current_user.id,
        product_id=recommendation.product_id,
        recommended_quantity=recommendation.recommended_quantity,
        reason=recommendation.reason,
    )
    db.add(db_recommendation)
    db.commit()
    db.refresh(db_recommendation)

    return build_recommendation_response(db_recommendation, product.name)


@router.post("/generate/{product_id}", response_model=RecommendationResponse)
def generate_recommendation(
    product_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    product = (
        db.query(Product)
        .filter(
            Product.id == product_id,
            Product.user_id == current_user.id,
        )
        .first()
    )

    if not product:
        raise HTTPException(status_code=404, detail="Product not found")

    forecast = (
        db.query(Forecast)
        .filter(
            Forecast.user_id == current_user.id,
            Forecast.product_id == product_id,
            Forecast.model_version == MODEL_VERSION,
        )
        .order_by(Forecast.forecast_date.desc(), Forecast.id.desc())
        .first()
    )

    inventory = db.query(Inventory).filter(Inventory.product_id == product_id).first()

    if not forecast or not inventory:
        raise HTTPException(
            status_code=404,
            detail="Forecast or Inventory data not found for the product",
        )

    if inventory.current_stock <= product.reorder_threshold:
        recommended_quantity = max(
            int(forecast.predicted_demand - inventory.current_stock),
            0,
        )
    else:
        recommended_quantity = 0

    reason = (
        f"Current inventory is {inventory.current_stock}, "
        f"forecasted demand is {forecast.predicted_demand}. "
        f"Recommended quantity is {recommended_quantity}."
    )

    risk_level, risk_score = calculate_recommendation_risk(
        inventory,
        product,
        forecast,
        recommended_quantity,
    )

    existing_recommendation = (
        db.query(Recommendation)
        .filter(
            Recommendation.user_id == current_user.id,
            Recommendation.product_id == product_id,
        )
        .first()
    )

    if existing_recommendation:
        existing_recommendation.recommended_quantity = recommended_quantity
        existing_recommendation.reason = reason
        db.commit()
        db.refresh(existing_recommendation)

        return build_recommendation_response(
            existing_recommendation,
            product.name,
            risk_level,
            risk_score,
        )

    db_recommendation = Recommendation(
        user_id=current_user.id,
        product_id=product_id,
        recommended_quantity=recommended_quantity,
        reason=reason,
    )

    db.add(db_recommendation)
    db.commit()
    db.refresh(db_recommendation)

    return build_recommendation_response(
        db_recommendation,
        product.name,
        risk_level,
        risk_score,
    )


@router.post("/generate_all", response_model=list[RecommendationResponse])
def generate_recommendations_for_all_products(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    products = db.query(Product).filter(Product.user_id == current_user.id).all()

    recommendations = []

    for product in products:
        forecast = (
            db.query(Forecast)
            .filter(
                Forecast.user_id == current_user.id,
                Forecast.product_id == product.id,
                Forecast.model_version == MODEL_VERSION,
            )
            .order_by(Forecast.forecast_date.desc(), Forecast.id.desc())
            .first()
        )

        inventory = db.query(Inventory).filter(Inventory.product_id == product.id).first()

        if not forecast or not inventory:
            continue

        if inventory.current_stock <= product.reorder_threshold:
            recommended_quantity = max(
                int(forecast.predicted_demand) - inventory.current_stock,
                0,
            )
        else:
            recommended_quantity = 0

        reason = (
            f"Current inventory is {inventory.current_stock}, "
            f"forecasted demand is {forecast.predicted_demand}. "
            f"Recommended quantity is {recommended_quantity}."
        )

        risk_level, risk_score = calculate_recommendation_risk(
            inventory,
            product,
            forecast,
            recommended_quantity,
        )

        existing_recommendation = (
            db.query(Recommendation)
            .filter(
                Recommendation.user_id == current_user.id,
                Recommendation.product_id == product.id,
            )
            .first()
        )

        if existing_recommendation:
            existing_recommendation.recommended_quantity = recommended_quantity
            existing_recommendation.reason = reason
            recommendations.append(
                (existing_recommendation, product.name, risk_level, risk_score)
            )
        else:
            db_recommendation = Recommendation(
                user_id=current_user.id,
                product_id=product.id,
                recommended_quantity=recommended_quantity,
                reason=reason,
            )
            db.add(db_recommendation)
            recommendations.append(
                (db_recommendation, product.name, risk_level, risk_score)
            )

    db.commit()

    responses = []

    for recommendation, product_name, risk_level, risk_score in recommendations:
        db.refresh(recommendation)
        responses.append(
            build_recommendation_response(
                recommendation,
                product_name,
                risk_level,
                risk_score,
            )
        )

    responses.sort(
        key=lambda recommendation: (
            -recommendation["recommended_quantity"],
            recommendation["product_name"].lower(),
            -recommendation["id"],
        )
    )

    return responses